---
- name: 构建环境变量
  import_tasks: vars-task.yml

- name: 初始化环境
  import_tasks: init-system-task.yml
  when: init == "1"

- name: 应用所需环境
  import_tasks: init-app-task.yml
  when: init == "1"

- name: 部署脚本
  import_tasks: depoly-task.yml
